### PR TITLE
Bump to support JupyterLab 4.0

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes https://github.com/jupyterlab-contrib/jupyterlab-open-url-parameter/issues/9

### CODE REVIEW

**Comment by yuvipanda** [comment]
This is the *minimum* required to build for 4.0, and I hope that's enough.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by yuvipanda** [comment]
@jtpio yay awesome. Can you make a PyPI release too?

**Comment by yuvipanda** [comment]
image

yay!

**Pull request merged**
